### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by iot-resister** [esp-rs/docs#1]
![](https://svgur.com/i/SMg.svg)

**Comment by MabezDev** [comment]
I like it! Is this something you made, or found?

**Comment by iot-resister** [comment]
I made it. :)

**Comment by MabezDev** [comment]
Looks really nice! Thank you very much :) 

My only concern is that it includes the Espressif logo, which we probably don't have permission to use :(

**Comment by iot-resister** [comment]
made another one 

![](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/bqQlJWYLxRDGzAudhyKyujxg)

**Comment by MabezDev** [comment]
Hi @iot-resister, we'd like to use the first logo! Do you give us permission to do so?

**Comment by iot-resister** [comment]
Sure!

**Comment by MabezDev** [comment]
Thank you for the Logo @iot-resister! I've just changed it :)
